<BackgroundColor@Widget>
    background_color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgba: root.background_color
        Rectangle:
            size: self.size
            pos: self.pos
# Now you can simply Mix the `BackgroundColor` class with almost
# any other widget... to give it a background.
<BLabel@Label+BackgroundColor>
    background_color: 0, 0, 0, 0


<MyScreenManager>:
    id:manager

    FirstScreen:
        id: first_screen
    FourthScreen:
    SecondScreen:
        id:second_screen
    ThirdScreen:



<FirstScreen>:
    name: '_first_screen_'
    #Label:

     #   text: "Hi I'm The First Screen"
    BoxLayout:
        id: first_screen_label
        canvas.before:
            Color:
                rgba: .2, .2, .2, 1
            Rectangle:
                pos: self.pos
                size: self.size
        padding:00

        orientation: "vertical"
        Image:
            source: 'logo.png'
        BoxLayout:
            padding:50
            canvas.before:
                Color:
                    rgba: 0, 0, 0, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            padding:30
            orientation:"horizontal"
            BLabel:
                size_hint:.3,.6
                background_color:.95,.45,.20,.8
                text:"Email:"
                halign :'justify'
                valign :'center'

            TextInput:
                size_hint:.6,.6
                valign :'center'

                text:'kevincwulff@gmail.com'
                id:email
        BoxLayout:
            padding:30
            orientation:"horizontal"
            BLabel:
                size_hint:.3,.6
                background_color:0,.2,.2,.4
                halign :'left'
                text:"Password:"
                halign :'justify'
                valign :'center'
            TextInput:
                size_hint:.6,.6
                text:''
                password:True
                id:password
        BLabel:
            text_size: self.size
            size_hint:1,1
            valign :'bottom'
            halign:'left'
            id:status

            background_color:.0,0,0,1
        BoxLayout:
            size_hint:1,.3
            orientation:"horizontal"

            Button:
                background_color:.95,.45,.20,1
                text:"Login"
                padding:50,50
                size_hint_x:5
                on_press:
                    root.login('fuck off',email,password)
                    root.manager.transition.direction = 'down'
                    #root.manager.current = '_fourth_screen_'

            Button:
                padding:150,150
                #text:"Demo"
                #Image:


                #background_normal:'menu100.png'
                size_hint:1,1
                halign:'center'
                valign:'center'
                width:50
                height:50

                    #source:'back.png'
                    #stretch:'True'

                on_press:
                    root.loadcache('fuck off',email,password)
                    root.manager.transition.direction = 'down'
                    root.manager.current = '_fourth_screen_'

#Flaticon.com
<SecondScreen>:
    name: '_second_screen_'
    #canvas.before:
    #    Rectangle:
    #        pos: self.pos
    #        size: self.size
    #        source: 'icon.png'
    BoxLayout:
        #default_size_hint:.2,.2
        orientation:"vertical"
        BLabel:
        #Show
            id: second_screen_label4
            #ize_hint:.13,None
            background_color:0,.4,0,.8
            #size_hint:2,.5
            font_size:60
            text_size:self.size
            halign:'center'
            valign: 'center'
            padding:5,0
        BLabel:
        #Away
            id: second_screen_label1
            #size_hint:.33,None
            background_color:.2,.4,0,.8
            size_hint:2,.5
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0
        BLabel:
        #Date
            id: second_screen_label
            #size_hint:.33,None
            background_color:.2,.4,0,.8
            size_hint:2,.5
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0

        BLabel:
        #Time
            id: second_screen_label2
            size_hint:2,.5
            background_color:0,.4,0,.8
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0
        BLabel:
        #jobid
            id: second_screen_label3
            #ize_hint:.13,None
            background_color:0,.4,0,.8
            size_hint:2,.5
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0

        BLabel:
        #place
            id: second_screen_label5
            #size_hint:.13,None
            background_color:1,.4,0,.8
            #size_hint:.13,None
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0
        BLabel
        #venue
            id: second_screen_label6
            #size_hint:.13,None
            background_color:0,.4,0,.8
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0

        BLabel:
        #client
            id: second_screen_label7
            #size_hint:.13,None
            background_color:0,.4,0,.8
            #size_hint:.13,None
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0
        BLabel
        #type
            id: second_screen_label8
            #size_hint:.13,None
            #size_hint:None,1
            background_color:1,.4,0,.8
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0
        BLabel:
        #pos
            id: second_screen_label9
            #size_hint:None,.5
            background_color:0,.4,0,.8
            #size_hint:.13,None
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0
        BLabel:
            id: second_screen_label10
            #size_hint:None,.5
            background_color:0,.4,1,.8
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0
        BLabel:
        #status
            id: second_screen_label11
            #size_hint:.13,None
            #background_color:color_1
            #size_hint:.13,None
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0
        BLabel
        #notes
            id: second_screen_label12
            size_hint:1,2
            background_color:0,.4,0,.8
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0

        BLabel
            id: second_screen_label13
            #size_hint:.13,None
            background_color:0,.4,0,.8
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0
        BLabel
            id: second_screen_label14
            #size_hint:.13,None
            background_color:0,.2,0,.8
            font_size:40
            text_size:self.size
            halign:'left'
            valign: 'center'
            padding:5,0

        BoxLayout:
            size_hint:1,1
            orientation:"horizontal"
            Button:
            #size_hint:.25,.53
                text:'back'

                #background_normal:'back.png'
                #stretch:True
                on_press:
                #root.__init__(self)
                    root.manager.transition.direction = 'down'
                    root.manager.current = '_fourth_screen_'
            Button:
                text:'Confirm'
            Button:
                padding:150,150
                #text:"Demo"
                #Image:


                background_normal:'tex.png'
                size_hint:1,1
                halign:'center'
                valign:'center'
                width:50
                height:50



<ThirdScreen>:
    name: '_third_screen_'
    BoxLayout:
        orientation:"vertical"
        #RV2:
        Button:
            background_normal:'tex.png'
            #size_hint:1,1
            halign:'center'
            valign:'center'
            width:50
            height:50
            text:'back'
            on_press:

                root.manager.transition.direction = 'down'
                root.manager.current = '_fourth_screen_'

<FourthScreen>:
    id:'WHAT'

    name: '_fourth_screen_'
    BoxLayout:
        orientation:"vertical"
        RV:
            size_hint:1,.9
        BoxLayout:
            #size_hint:.3,.6
            #background_normal:'back150.png'

            size_hint:.25,.1
            Button:
                halign:'center'
                valign:'center'

                text:'back'
                on_press:
                    #root.__init__(self)
                    root.manager.transition.direction = 'down'
                    root.manager.current = '_first_screen_'
            Button:
                text:'update'
                on_press:root.parent.update()

    #Label:
    #    id: fourth_screen_label
    #    text: "Hi I'm The Fourth Screen"


<SelectableLabel>:
    # Draw a background to indicate selection
    canvas.before:
        Color:
            rgba: (.0, 0.9, .1, .3) if self.selected else (0, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    #size:self.texture_size
    #text_size:root.width,None
    label1_text: 'label 1 text'
    label2_text: 'label 2 text'

    label3_text: 'label 3 text'

    label4_text: 'label 4 text'
    label5_text: 'label 5 text'
    label6_text: 'label 6 text'
    label7_text: 'label 7 text'
    label8_text: 'label 8 text'
    label9_text: 'label 9 text'
    label10_text: 'label 10 text'
    label11_text: 'label 11 text'


    #pos: self.pos
    #size: self.size
    BLabel:
    #DATE
        #texture_size:.5,.5
        #text_size:self.size
        text_sdize:None,None
        id: id_label1
        text: root.label1_text
        size_hint:.23,None
        #size:10,10
        #width:200
        #height:100
        background_color:1,.3,0,.8
        #halign:'left'
        #valign:'top'
        font_size:30
        #padding:0
        #text_size:100,None
        #on_press:
            #root.manager.current='wow'

    BLabel:
    #TIME
        #size:self.texture_size
        #text_size:root.width,None
        id: id_label2
        text: root.label2_text
        size_hint:.13,None
        background_color:0,.4,0,.8
        font_size:30

    BLabel:
    #Type
        #size:self.texture_size
        #text_size:root.width,None
        id: id_label8
        text: root.label8_text
        #size_hint:50,50
        background_color:0,.4,1,.8
        size_hint:.12,None
        font_size:30



    BLabel:
    #Position
        #size:self.texture_size
        #text_size:root.width,None
        id: id_label9
        text: root.label9_text
        size_hint:.15,None
        background_color:.4,.2,.2,.8
        font_size:30
    BLabel:
    #show
        id: id_label4
        #text: root.label4_text
        #size_hint:170,170
        background_color:1,.8,1,.8
        size_hint:.4,None
        font_size:30
        text_size:self.size
        halign:'left'
        valign: 'center'
        padding:5,0
    BLabel:
    #Place
        #size:self.texture_size
        #text_size:root.width,None
        id: id_label5
        text: root.label5_text
        #size_hint:50,50
        background_color:.5,.3,1,.8
        size_hint:.7,None
        font_size:30
        text_size:self.size
        halign:'left'
        valign: 'center'
        padding:5,0

    BLabel:
        id: id_label6
        text: root.label6_text
        #size_hint:170,170
        background_color:1,.4,.2,.8
        size_hint:.6,None
        font_size:30
        text_size:self.size
        halign:'left'
        valign: 'center'
        padding:5,0

    BLabel:
        id: id_label11
        text: root.label11_text
        #size_hint:170,170
        background_color:.5,.4,0,.8
        size_hint:.5,None
        font_size:60
        text_size:self.size
        halign:'left'
        valign: 'center'
        padding:5,0

    BLabel:
    #jobid
        id: id_label3
        text: root.label3_text
        #size_hint:170,170
        background_color:1,1,1,.8
        size_hint:.2,None
        font_size:30
        text_size:self.size
        halign:'left'
        valign: 'center'
        padding:5,0



<RV>:
    name: '_fourth_screen3_'
    viewclass: 'SelectableLabel'
    SelectableRecycleBoxLayout:
        default_size: dp(100), dp(40)
        default_size_hint: .9,None
        #size_hint_y: None
        default_text_size:10
        height: self.minimum_height
        orientation: 'vertical'
        multiselect: False
        touch_multiselect: False
        size_hint_y: None
        size_hint_x: 3
        height: self.minimum_height
        width: self.minimum_width




