<MyScreenManager>:
    FirstScreen:
        id: first_screen
    FourthScreen:
    SecondScreen:
    ThirdScreen:


<FirstScreen>:
    name: '_first_screen_'
    #Label:

     #   text: "Hi I'm The First Screen"
    BoxLayout:
        id: first_screen_label
        canvas.before:
            Color:
                rgba: .2, .2, .2, 1
            Rectangle:
                pos: self.pos
                size: self.size
        padding:00

        orientation: "vertical"
        Image:
            source: 'icon.png'
        BoxLayout:
            padding:50
            canvas.before:
                Color:
                    rgba: .2, .3, .2, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            padding:30
            orientation:"horizontal"
            Label:
                background_color: 1, 0, 0, 1
                text:"Email:"
                halign :'justify'

            TextInput:

                text:'kevincwulff@gmail.com'
                id:email
        BoxLayout:
            padding:30
            orientation:"horizontal"
            Label:
                halign :'left'
                text:"Password:"
            TextInput:

                text:''
                password:True
                id:password
        BoxLayout:
            orientation:"horizontal"

            Button:
                text:"Login"
                padding:50,50
                on_press:
                    root.login('fuck off',email,password)
                    root.manager.transition.direction = 'down'
                    #root.manager.current = '_fourth_screen_'

            Button:
                text:"Demo"
                padding:50,50
                on_press:
                    #root.loadcache('fuck off',email,password)
                    root.manager.transition.direction = 'down'
                    root.manager.current = '_fourth_screen_'


<SecondScreen>:
    name: '_second_screen_'
    Label:
        id: second_screen_label
        text: "Hi I'm The Second Screen"

<ThirdScreen>:
    name: '_third_screen_'
    Label:
        id: third_screen_label
        text: "Hi I'm The Third Screen"

<FourthScreen>:

    name: '_fourth_screen_'
    BoxLayout:
        orientation:"vertical"
        RV:
        Button:
            text:'re'
            on_press:
                #root.__init__(self)
                root.manager.transition.direction = 'down'
                root.manager.current = '_fourth_screen_'
    #Label:
    #    id: fourth_screen_label
    #    text: "Hi I'm The Fourth Screen"


<SelectableLabel>:
    # Draw a background to indicate selection
    canvas.before:
        Color:
            rgba: (.0, 0.9, .1, .3) if self.selected else (0, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    label1_text: 'label 1 text'
    label2_text: 'label 2 text'

    label3_text: 'label 3 text'
    label4_text: 'label 4 text'
    pos: self.pos
    size: self.size
    Label:
        id: id_label1
        text: root.label1_text
    Label:
        id: id_label2
        text: root.label2_text
    Label:
        id: id_label3
        text: root.label3_text

    Label:
        id: id_label4
        text: root.label4_text

<RV>:
    name: '_fourth_screen3_'
    viewclass: 'SelectableLabel'
    SelectableRecycleBoxLayout:
        default_size: None, dp(56)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        multiselect: True
        touch_multiselect: True